import { StyleSheet } from 'react-native';

export const createStyles = (isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#121212' : '#ffffff',
    },
    image: {
      width: 120,
      height: 120,
      marginBottom: 20,
    },
    card: {
      backgroundColor: isDark ? '#1e1e1e' : 'white',
      padding: 30,
      borderRadius: 20,
      width: '100%',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 6,
      marginBottom: 20,
      borderWidth: isDark ? 1 : 0,
      borderColor: isDark ? '#333' : 'transparent',
    },
    title: {
      fontFamily: 'Poppins',
      fontSize: 20,
      fontWeight: '600',
      marginBottom: 10,
      textAlign: 'center',
      color: isDark ? '#eee' : '#333',
    },
    subtitle: {
      fontFamily: 'Poppins',
      fontSize: 14,
      textAlign: 'center',
      color: isDark ? '#ccc' : '#555',
      marginBottom: 25,
    },
    button: {
      backgroundColor: isDark ? '#4461c2' : '#4b7bec',
      paddingVertical: 14,
      paddingHorizontal: 30,
      borderRadius: 30,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 4,
      marginVertical: 10,
      width: '100%',
      maxWidth: 300,
      alignItems: 'center',
    },
    buttonHover: {
      backgroundColor: isDark ? '#3552a0' : '#357ABD',
    },
    buttonPressed: {
      backgroundColor: isDark ? '#2d4b91' : '#2e6bbf',
    },
    buttonText: {
      color: 'white',
      fontSize: 16,
      fontFamily: 'Poppins',
      fontWeight: '600',
    },
    scrollContainer: {
      paddingVertical: 40,
      paddingHorizontal: 20,
      alignItems: 'center',
    },
    infoSection: {
      backgroundColor: isDark ? '#1e1e1e' : 'white',
      padding: 30,
      borderRadius: 20,
      width: '100%',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 6,
    },
    infoTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 10,
      textAlign: 'center',
      color: isDark ? '#eee' : '#333',
    },
    infoText: {
      fontSize: 16,
      lineHeight: 24,
      textAlign: 'center',
      color: isDark ? '#ccc' : '#555',
    },
    footer: {
      marginTop: 40,
      marginBottom: 20,
      alignItems: 'center',
    },
    footerText: {
      fontSize: 14,
      color: isDark ? '#999' : '#777',
      marginVertical: 2,
    },
    header: {
      marginTop: 40,
      marginBottom: 10,
      alignItems: 'center',
    },
    headerText: {
      fontSize: 36,
      fontWeight: '800',
      color: isDark ? '#9ec3ff' : '#4b7bec',
      textAlign: 'center',
      textShadowColor: isDark ? '#222' : '#aaa',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
  });

